# safeguarding_words = ["hurt", "fell", "sick", "choking", "died", "sex", "religion", "racist",
#                       "bruise", "wound", "bleeding", "hit", "punch", "slap", "kick",
#                       "scratch", "bite", "burn", "indecent", "inappropriate",
#                       "unprofessional", "disrespect", "harass", "threat", "scream",
#                       "yell", "insult", "slur", "almost fell", "uncomfortable", "ass", "stupid", "bitch",
#                       "unsafe", "abuse", "violence", "neglect", "bully", "misconduct",
#                       "offensive", "vulgar", "invasive", "intimidate", "disturb",
#                       "manipulate", "aggressive", "injury", "trauma", "pain",
#                       "harmful", "hate", "derogatory", "profanity", "unethical",
#                       "improper", "exploit", "violate", "invasion of privacy",
#                       "non-consensual", "demeaning", "obscene", "predatory",
#                       "misbehavior", "molest", "offend", "hazardous", "dangerous",
#                       "unauthorized", "unwanted", "unlawful", "vulgar",
#                       "disparage", "belittle", "degrading", "coerce",
#                       "intolerant", "provocative", "reprehensible",
#                       "harrassment", "unruly", "aggression", "hateful",
#                       "unsafe", "unacceptable", "hurtful", "hazard",
#                       "injurious", "maltreat", "violation", "controversial",
#                       "discomfort", "unseemly", "unworthy", "victimize",
#                       "discrimination", "prejudice", "bigotry",
#                       "derogative", "injurious", "improper",
#                       "vulgarity", "cruelty", "unprofessionalism",
#                       "indecency", "abusive", "hateful", "threatening",
#                       "intolerant", "racism", "sexism", "disrespectful",
#                       "profane", "disparaging", "unethical", "intimidating",
#                       "harm", "vandalize", "exploitative", "hurtful",
#                       "invasion", "harsh", "offensive", "insulting",
#                       "insensitive", "vicious", "wicked", "unlawful",
#                       "wrong", "danger", "vulgar", "explicit",
#                       "provoking", "objectionable", "hatefulness",
#                       "disgusting", "abhorrent", "destructive",
#                       "menacing", "unsuitable", "off-color",
#                       "off-putting", "lewd", "pornographic",
#                       "indecorous", "impolite", "discreditable",
#                       "calumnious", "immodest", "intrusive",
#                       "disorderly", "indecorous", "outrageous",
#                       "disreputable", "insulting", "intolerable",
#                       "unauthorized", "provocative", "obscene",
#                       "demeaning", "abusive", "offensive",
#                       "hurtful", "injurious", "exploit",
#                       "discomfort", "unseemly", "victimize",
#                       "discrimination", "prejudice", "bigotry",
#                       "derogatory", "injurious", "improper",
#                       "vulgarity", "cruelty", "unprofessionalism",
#                       "indecency", "abusive", "hateful",
#                       "threatening", "intolerant", "racism",
#                       "sexism", "disrespectful", "profane",
#                       "disparaging", "unethical", "intimidating",
#                       "harm", "vandalize", "exploitative",
#                       "hurtful", "invasion", "harsh",
#                       "offensive", "insulting", "insensitive",
#                       "vicious", "wicked", "unlawful",
#                       "wrong", "danger", "vulgar",
#                       "explicit", "provoking", "objectionable",
#                       "hatefulness", "disgusting", "abhorrent",
#                       "destructive", "menacing", "unsuitable",
#                       "off-color", "off-putting", "lewd",
#                       "pornographic", "indecorous", "impolite",
#                       "discreditable", "calumnious", "immodest",
#                       "intrusive", "disorderly", "indecorous",
#                       "outrageous", "disreputable", "insulting",
#                       "intolerable", "disgraceful", "repugnant",
#                       "vulgarism", "atrocious", "injurious",
#                       "indecent", "menacing", "reprehensible",
#                       "intolerable", "abominable", "reprehensible",
#                       "disgusting", "egregious", "immoral",
#                       "indecent", "loathsome", "scandalous",
#                       "unworthy", "degrading", "reproachful",
#                       "unprincipled", "corrupt", "debauched",
#                       "unethical", "unscrupulous", "shameful",
#                       "repulsive", "wretched", "unscrupulous",
#                       "repulsive", "unscrupulous", "shameful",
#                       "repulsive", "wretched", "disreputable",
#                       "infamous", "unbecoming", "deplorable",
#                       "objectionable", "discreditable", "sordid",
#                       "contemptible", "atrocious", "malicious",
#                       "offensive", "intolerant", "dishonorable",
#                       "offensive", "intolerant", "dishonorable",
#                       "intolerant", "discourteous", "sinful",
#                       "inconsiderate", "ungracious", "disobedient",
#                       "suspicious", "boorish", "unlawful",
#                       "criminal", "wrongful", "dangerous",
#                       "menacing", "destructive", "unfit",
#                       "deceptive", "unreliable", "unprofessionalism",
#                       "incompetent", "imprudent", "negligent",
#                       "inattentive", "inadequate", "inefficient",
#                       "inept", "insecure", "uncaring",
#                       "ineffective", "inappropriate", "unauthorized",
#                       "unapproved", "unethical", "fraudulent",
#                       "untruthful", "unjust", "unfair",
#                       "exploitative", "manipulative", "domineering",
#                       "controlling", "intimidating", "oppressive",
#                       "intrusive", "invasive", "unwanted",
#                       "intrusive", "off-putting", "unwelcome",
#                       "intrusive", "degrading", "demeaning",
#                       "humiliating", "embarrassing", "belittling",
#                       "disparaging", "patronizing", "condescending",
#                       "sarcastic", "dismissive", "disapproving",
#                       "disheartening", "disconcerting", "distressing",
#                       "disturbing", "alarming", "upsetting",
#                       "unsettling", "unpleasant", "provocative",
#                       "incendiary", "inflammatory", "provoking",
#                       "aggravating", "irritating", "annoying",
#                       "bothersome", "offensive", "obscene",
#                       "repugnant", "repulsive", "revolting",
#                       "disgusting", "nauseating", "objectionable",
#                       "insulting", "abusive", "injurious",
#                       "hurtful", "damaging", "injurious",
#                       "dangerous", "hazardous", "risky",
#                       "perilous", "precarious", "uncertain",
#                       "unstable", "insecure", "prejudiced",
#                       "biased", "discriminatory", "intolerant",
#                       "insensitive", "disrespectful", "unfriendly",
#                       "hostile", "unwelcoming", "distant",
#                       "aloof", "unapproachable", "unsupportive",
#                       "dismissive", "disinterested", "uncaring",
#                       "unresponsive", "inattentive", "neglectful",
#                       "inconsiderate", "uncooperative", "unresponsive",
#                       "stubborn", "obstinate", "unyielding",
#                       "unhelpful", "uncooperative", "unaccommodating",
#                       "inflexible", "unforgiving", "uncompromising",
#                       "unyielding", "stubborn", "self-centered",
#                       "egotistical", "narcissistic", "demanding",
#                       "overbearing", "condescending", "patronizing",
#                       "manipulative", "deceptive", "dishonest",
#                       "untrustworthy", "unreliable", "disingenuous",
#                       "insincere", "manipulative", "calculating",
#                       "selfish", "greedy", "self-serving",
#                       "manipulative", "dishonest", "corrupt",
#                       "fraudulent", "untruthful", "lying",
#                       "misleading", "deceitful", "concealing",
#                       "secretive", "scheming", "conniving",
#                       "cunning", "crafty", "devious",
#                       "unethical", "immoral", "unprincipled",
#                       "unscrupulous", "corrupt", "unfair",
#                       "biased", "discriminatory", "partial",
#                       "prejudiced", "intolerant", "bigoted",
#                       "insensitive", "inconsiderate", "thoughtless",
#                       "neglectful", "unresponsive", "apathetic",
#                       "indifferent", "unfeeling", "unsympathetic",
#                       "uncompassionate", "callous", "cold-hearted",
#                       "heartless", "cruel", "mean-spirited",
#                       "unkind", "harsh", "hurtful",
#                       "spiteful", "malicious", "vindictive",
#                       "hateful", "hostile", "aggressive",
#                       "angry", "bitter", "resentful",
#                       "irritable", "impatient", "moody",
#                       "irrational", "unstable", "temperamental",
#                       "volatile", "explosive", "reckless",
#                       "impulsive", "rash", "careless",
#                       "negligent", "inattentive", "unreliable",
#                       "inconsistent", "unpredictable", "undependable",
#                       "uncontrollable", "overemotional", "neurotic",
#                       "overreacting", "dramatic", "attention-seeking",
#                       "manipulative", "demanding", "controlling",
#                       "domineering", "bossy", "overbearing",
#                       "aggressive", "bullying", "threatening",
#                       "intimidating", "frightening", "menacing",
#                       "harassing", "harsh", "cruel",
#                       "uncaring", "unfeeling", "unsympathetic",
#                       "indifferent", "aloof", "distant",
#                       "unresponsive", "self-centered", "egocentric",
#                       "narcissistic", "egotistical", "selfish",
#                       "arrogant", "condescending", "patronizing",
#                       "self-absorbed", "entitled", "pompous",
#                       "superior", "judgmental", "opinionated",
#                       "dogmatic", "rigid", "close-minded",
#                       "intolerant", "prejudiced", "bigoted",
#                       "narrow-minded", "ignorant", "insensitive",
#                       "thoughtless", "inconsiderate", "unsympathetic",
#                       "apathetic", "indifferent", "unfeeling",
#                       "heartless", "cold", "callous",
#                       "uncompassionate", "cruel", "mean",
#                       "vindictive", "spiteful", "malicious",
#                       "hateful", "hostile", "aggressive",
#                       "angry", "irritable", "impatient",
#                       "moody", "unstable", "temperamental",
#                       "volatile", "impulsive", "reckless",
#                       "careless", "negligent", "inconsistent",
#                       "unpredictable", "undependable", "unreliable",
#                       "uncontrollable", "overemotional", "neurotic",
#                       "dramatic", "attention-seeking", "manipulative",
#                       "demanding", "controlling", "bossy",
#                       "overbearing", "aggressive", "bullying",
#                       "threatening", "intimidating", "harassing",
#                       "menacing", "harsh", "uncaring",
#                       "unfeeling", "indifferent", "aloof",
#                       "distant", "unresponsive", "self-centered",
#                       "egocentric", "narcissistic", "egotistical",
#                       "selfish", "arrogant", "condescending",
#                       "patronizing", "self-absorbed", "entitled",
#                       "pompous", "superior", "judgmental",
#                       "opinionated", "dogmatic", "rigid",
#                       "close-minded", "intolerant", "prejudiced",
#                       "bigoted", "narrow-minded"]
safeguarding_words = ["drink Cosmo"]
